/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.github.junit.params.parser.list;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LinkedListTest {

    private static final String ONE = "one";
    private static final String TWO = "two";

    @Test
    void testConstructor() {
        LinkedList list = new LinkedList();
        assertEquals(0, list.size());
    }

    @Test
    void testAdd() {
        LinkedList list = new LinkedList();

        list.add(ONE);
        assertEquals(1, list.size());
        assertEquals(ONE, list.get(0));

        list.add(TWO);
        assertEquals(2, list.size());
        assertEquals(TWO, list.get(1));
    }

    @Test
    void testRemove() {
        LinkedList list = new LinkedList();

        list.add(ONE);
        list.add(TWO);
        assertTrue(list.remove(ONE));

        assertEquals(1, list.size());
        assertEquals(TWO, list.get(0));

        assertTrue(list.remove(TWO));
        assertEquals(0, list.size());
    }

    @Test
    public void testRemoveMissing() {
        LinkedList list = new LinkedList();

        list.add(ONE);
        list.add(TWO);
        assertFalse(list.remove("three"));
        assertEquals(2, list.size());
    }

}
