/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.github.junit.params.parser.app;

import com.github.junit.params.parser.list.LinkedList;
import org.apache.commons.text.WordUtils;

import static com.github.junit.params.parser.app.MessageUtils.getMessage;
import static com.github.junit.params.parser.utilities.StringUtils.join;
import static com.github.junit.params.parser.utilities.StringUtils.split;

public final class App {

    private App() {}

    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }

}
