/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.junit.params.parser.app;

class MessageUtils {

    public static String getMessage() {
        return "Hello      World!";
    }

}
